static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          deprecated_v1: true
          value:
            stat_prefix: ingress_http
            route_config:
              virtual_hosts:
              - routes:
                - prefix: "/"
                  timeout_ms: 0
                  cluster: cluster1
                domains:
                - "*"
                name: local_service
            filters:
            - name: router
              config: {}
            codec_type: auto
    use_original_dst: true
  clusters:
  - name: cluster1
    type: ORIGINAL_DST
    connect_timeout: 6s
    lb_policy: ORIGINAL_DST_LB
    dns_lookup_family: V4_ONLY
cluster_manager: {}
watchdog: {}
admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
